export enum ScreenName {
  Welcome = 'Welcome',
  Login = 'Login',
  Signup = 'Signup',
  App = 'App',
  Home = 'Home',
  Search = 'Search',
  Library = 'Library',
  AuthNavigator = 'AuthNavigator',
  AppNavigator = 'AppNavigator',
  TabNavigator = 'TabNavigator',
  HomeNavigator = 'HomeNavigator',
  LibraryNavigator = 'LibraryNavigator',
  SearchNavigator = 'SearchNavigator',
}
